name: Upload Docs iOS

on:
  pull_request:
    types:
      - opened
    branches:
      - 'master'
  push:
    branches:
      - '**'
      
jobs:
  upload-docs:

    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Commit TXT file to docs branch
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git fetch || git checkout -b docs
        echo "This is a generated file." > generated_file.txt
        git add generated_file.txt
        git commit -m "Add generated TXT file"
        git push origin docs
      env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
